name: real-time-object-counter
channels:
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=11.8
  - pip
  - pip:
      - numpy==1.24.4
      - opencv-python==4.8.1.78
      - ultralytics==8.0.200
      - rich==13.7.0
      - pyyaml==6.0.1